cities = ['Adelaide',
          'Aden',
          'Ahmedabad',
          'Al Fashir',
          'Algiers',
          'Alice Springs',
          'Amsterdam',
          'Anadyr',
          'Anchorage',
          'Araguaina',
          'Asuncion',
          'Athens',
          'Atlanta',
          'Auckland',
          'Baghdad',
          'Bamako',
          'Bangalore',
          'Bangkok',
          'Barcelona',
          'Bariloche',
          'Barrow',
          'Beijing',
          'Beira',
          'Beirut',
          'Belem',
          'Belfast',
          'Belgrade',
          'Benghazi',
          'Bergen',
          'Berlin',
          'Bern',
          'Bismarck',
          'Bogota',
          'Bordeaux',
          'Boston',
          'Brasilia',
          'Brisbane',
          'Broken Hill',
          'Broome',
          'Brussels',
          'Bucharest',
          'Buenos Aires',
          'Butwal',
          'Cairns',
          'Cairo',
          'Calgary',
          'Campo Grande',
          'Cancun',
          'Capetown',
          'Caracas',
          'Casablanca',
          'Cebu',
          'Charleston',
          'Chengdu',
          'Chicago',
          'Chihuahua',
          'Christchurch',
          'Cincinnati',
          'Copenhagen',
          'Cordoba Argentina',
          'Cordoba Spain',
          'Cuiaba',
          'Cuzco',
          'Dakar',
          'Dallas',
          'Darwin',
          'Delhi',
          'Denver',
          'Detroit',
          'Dhaka',
          'Djibouti',
          'Durban',
          'Easter Island',
          'Edmonton',
          'Fairbanks',
          'Fortaleza',
          'Georgetown',
          'Geraldton',
          'Glasgow',
          'Goose Bay',
          'Guangzhou',
          'Guatemala',
          'Hammerfest',
          'Hanoi',
          'Harare',
          'Harbin',
          'Havana',
          'Helsinki',
          'Hilo',
          'Hobart',
          'Hong Kong',
          'Honolulu',
          'Houston',
          'Hyderabad',
          'In Salah',
          'Inuvik',
          'Iqualit',
          'Iquitos',
          'Istanbul',
          'Jakarta',
          'Jerusalem',
          'Johannesburg',
          'Juba',
          'Juneau',
          'Kabul',
          'Kaduna',
          'Kalgoorlie',
          'Kampala',
          'Kananga',
          'Kandahar',
          'Kansas City',
          'Karachi',
          'Katherine',
          'Ketchikan',
          'Khartoum',
          'Kiev',
          'Kinhasa',
          'Kisangani',
          'Kolkata',
          'Kuching',
          'Kuwait City',
          'La Paz',
          'Lagos',
          'Las Vegas',
          'Lhasa',
          'Lilongwe',
          'Lima',
          'Lisbon',
          'Livingstone',
          'Lobito',
          'London',
          'Los Angeles',
          'Lulea',
          'Lyon',
          'Madrid',
          'Magadan',
          'Mahajanga',
          'Manaus',
          'Manchester',
          'Manila',
          'Melbourne',
          'Mexico City',
          'Miami',
          'Minneapolis',
          'Minsk',
          'Mogadishu',
          'Mombasa',
          'Monrovia',
          'Monterrey',
          'Montreal',
          'Moscow',
          'Mount Isa',
          'Mumbai',
          'Munich',
          'Murmansk',
          'Muscat',
          'Nagasaki',
          'Nairobi',
          'Nanping',
          'Naples',
          'New Orleans',
          'New York',
          'Newman',
          'Nome',
          'Norilsk',
          'Novosibirsk',
          'Nuuk',
          'Oaxaca',
          'Orlando',
          'Osaka',
          'Oslo',
          'Ottawa',
          'Oulu',
          'Padang',
          'Palu',
          'Panama',
          'Paris',
          'Perm',
          'Perth',
          'Pevek',
          'Philadelphia',
          'Phoenix',
          'Port Elizabeth',
          'Port Hedland',
          'Port Moresby',
          'Port Sudan',
          'Portland',
          'Porto Velho',
          'Prague',
          'Punta Arenas',
          'Quebec',
          'Quito',
          'Rangoon',
          'Recife',
          'Reykjavik',
          'Riga',
          'Rio de Janeiro',
          'Riyadh',
          'Rockhampton',
          'Rome',
          'Salt Lake City',
          'Salvador',
          'San Diego',
          'San Francisco',
          'San Jose',
          'Santiago',
          'Santo Domingo',
          'Sao Paolo',
          'Sapporo',
          'Saskatoon',
          'Seattle',
          'Sendai',
          'Seoul',
          'Shanghai',
          'Shenyang',
          'Singapore',
          'Spokane',
          'St. Louis',
          'St. Petersburg',
          'Stockholm',
          'Sydney',
          'Taipei',
          'Tbilisi',
          'Tehran',
          'Teresina',
          'Thunder Bay',
          'Tiksi',
          'Timbuktu',
          'Tokyo',
          'Toronto',
          'Tripoli',
          'Trondheim',
          'Ulan Bator',
          'Urumqi',
          'Vancouver',
          'Venice',
          'Vienna',
          'Vladivostok',
          'Volgograd',
          'Warsaw',
          'Washington, D.C.',
          'Wellington',
          'Whitehorse',
          'Windhoek',
          'Winnipeg']
